readme: Improve markdown, use table
sonyxperiadev/device-sony-ganges pull request #42
Opened 2021-02-05 18:05 UTC by Haxk20

Based on:
https://github.com/sonyxperiadev/device-sony-edo/commit/2f89cb6fc39fcbce02b0c1382fb34fa9357fd6ee

2021-02-06 13:08 UTC, MarijnS95 commented on README.md
> +| Device | Codename | Chip |
```suggestion
| Device | Codename | SoC |
```

2021-02-06 22:30 UTC, Haxk20 commented on README.md
> +| Device | Codename | Chip |
yup will do

2021-02-08 00:20 UTC, MarijnS95 requested changes

2021-02-08 00:20 UTC, MarijnS95 commented on README.md
> +### Supported devices:
```suggestion
### Supported devices
```

2021-02-12 08:30 UTC, merged